---
kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: apache-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: main

  template:
    metadata:
      name: apache-pod
      labels:
        app: main
    spec:
      containers:
        - name: apache-container
          image: httpd:2.2
          ports:
          - containerPort: 80

