apiVersion: v1
kind: Pod
metadata:
  name: empty-pod
spec:
  containers:
  - name: web-server
    image: nginx:1.14
    ports:
    - containerPort: 80
    # 볼륨 마운트
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
  # 볼륨 정의
  volumes:
  - name: html
    emptyDir: {}
  # 인덱스 파일이 없는 상태이므로, 요청시 403
  # kubectl exec empty-pod -it -- /bin/bash
  # echo 'hello world' > /usr/share/nginx/html/index.html
