---
kind: Pod
apiVersion: v1
metadata:
  name: web
spec:
  containers:
    - name: nginx
      image: nginx:1.14
      ports:
      - containerPort: 80
      volumeMounts:
      # mout /webdata /usr/share/nginx/html
        - name:  html
          mountPath:  /usr/share/nginx/html

  volumes:
  - name:  html
    hostPath: 
      path: /webdata
      