kind: Deployment
apiVersion: apps/v1
metadata:
  name: rolling-deploy
  annotations:
    kubernetes.io/change-cause: version 3.0
spec:
  selector:
    matchLabels:
      app: web
      version: stable
  replicas: 3
  template:
    metadata:
      name: rolling-pod
      labels:
        app: web
        version: stable
    spec:
      containers:
      - name: rolling-container
      # 레코드하기위해 어노테이션과 같은 이미지 줬음
        image: whatwant/node-web:3.0
        ports:
        - containerPort: 8080

