---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: webui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: headless-service
spec:
  type: ClusterIP
  clusterIP: None
  # None은 생략하면 안됨

  selector:
    app: webui
  ports:
  - port: 80
    targetPort: 80

