apiVersion: v1
kind: Pod
metadata:
  name: liveness-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 3600

    # 라이브니스 프로브 사용
    livenessProbe:
      exec:
        command:
        - ls
        - /tmp/healthy
      # 라이브니스 프로브 매개 변수 설정
      # 시작 후 10초 뒤 부터 점검 시작하라
      initialDelaySeconds: 10
      # 5초마다 점검하라
      periodSeconds: 5
      timeoutSeconds: 1
      successThreshold: 1
      failureThreshold: 2