---
kind: Pod
apiVersion: v1
metadata:
  name: myweb
spec:
  containers:
    - name: myweb-container
      image: nginx:1.14
      ports:
        - containerPort: 80

      resources:
          requests:
            cpu: "200m"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1Gi"

      env:
        - name: DB_ID
          value: developer
        - name: DB_PASS
          value: developer
      