apiVersion: v1
kind: Pod
metadata:
  labels:
    app: webui
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    #resources: {}
  # 포워드 DNS, 가장 먼저 물어보는 DNS 서버
  #dnsPolicy: ClusterFirst
  #restartPolicy: Always
#status: {}
