---
kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod-resource
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          cpu: "1"
          memory: "500Mi"
