---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-pool
  namespace: metallb-system
spec:
  addresses:
    # 아래 IP 주소 풀을 자신이 주고 싶은 대역으로 변경한다.
    - 192.168.10.20-192.168.10.30
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2
  namespace: metallb-system

