---
kind: ReplicationController
apiVersion: v1
metadata:
  name: rc-mainui
spec:
  replicas: 2
  selector:
    app: main
    rel: stable
  template:
    metadata:
      name: apache-pod
      labels:
        app: main
        rel: stable
    spec:
      containers:
      - name: apache-container
        image: httpd:2.2
        ports:
          - containerPort: 80


