---
kind: Pod
apiVersion: v1
metadata:
  name: pod-annotation
  # 주석
  annotations:
    builder: "NSH(thgus296@naver.com)"
    buildDate: "2025-10-01"
    # 아래 registry 참고했음
    imageRegistry: "docker.io/library/nginx:1.14"
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    ports:
    - containerPort: 80