apiVersion: v1
kind: Pod
metadata:
  name: genid-stone
spec:
  containers:
  - name: fakeid
    image: nam3/genid:env
    envFrom:
    - configMapRef:
        name: myconfigmap
    volumeMounts:
    - name: html
      mountPath: /webdata
  - name: web-server
    image: nginx:1.24
    volumeMounts: 
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
  volumes:
  - name: html
    emptyDir: {}